<a href="https://colab.research.google.com/github/JamesForrest87/Project-4/blob/main/Project4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# import pandas as pd
# from sqlalchemy import create_engine

# # Create engine to male_fertility.sqlite
# file_path = "/content/drive/MyDrive/Colab Notebooks/male_fertility.sqlite"
# engine = create_engine(f"sqlite:///{file_path}")

# # Define your SQL query
# sql_query = "SELECT * FROM male_sperm"

# # Load data into a DataFrame using pd.read_sql_query
# male_sperm_df = pd.read_sql_query(sql_query, engine)

# # Display the first few rows of the DataFrame
# print(male_sperm_df.head())

AttributeError: 'OptionEngine' object has no attribute 'execute'

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

import sqlalchemy

from sqlalchemy.ext.automap import automap_base

from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
from sqlalchemy import inspect
from sqlalchemy import text

In [2]:
file_path = "/content/drive/MyDrive/Colab Notebooks/male_fertility.sqlite"
# #################################################
# # Database Setup
# #################################################
# # create engine to hawaii.sqlite
engine = create_engine(f"sqlite:///{file_path}")
insp = inspect(engine)
print(insp.get_table_names())
# # reflect an existing database into a new model
# base = automap_base()
# # # # reflect the tables
# base.prepare(autoload_with=engine)
# base.classes.keys()
session = Session(bind=engine)

['male_sperm']

In [3]:
from sqlalchemy import text

with engine.connect() as connection:
    result = connection.execute(text("SELECT * FROM male_sperm"))
    for row in result:
        print(row)

(1, 2, 1, 1, 1, 1, 1, 6, 1, 4, 7, 3)
(2, 2, 1, 1, 1, 2, 1, 6, 1, 3, 4, 1)
(3, 2, 1, 1, 1, 2, 1, 6, 1, 5, 7, 1)
(4, 3, 1, 1, 2, 1, 2, 5, 1, 5, 10, 1)
(5, 2, 1, 1, 1, 1, 1, 6, 1, 3, 5, 1)
(6, 2, 1, 1, 1, 2, 1, 7, 1, 4, 5, 2)
(7, 2, 1, 1, 1, 1, 1, 6, 1, 5, 4, 3)
(8, 2, 1, 1, 1, 2, 1, 7, 1, 4, 1, 5)
(9, 3, 1, 1, 2, 3, 1, 6, 1, 5, 1, 5)
(10, 3, 1, 1, 1, 2, 1, 5, 1, 5, 5, 3)
(11, 2, 1, 1, 1, 2, 1, 7, 1, 4, 7, 7)
(12, 1, 1, 1, 1, 1, 1, 6, 1, 5, 2, 1)
(13, 1, 1, 1, 1, 1, 1, 6, 1, 4, 1, 3)
(14, 2, 3, 3, 1, 2, 1, 5, 1, 4, 6, 1)
(15, 2, 1, 1, 1, 1, 1, 7, 1, 4, 6, 1)
(16, 3, 1, 1, 1, 2, 1, 5, 1, 5, 6, 3)
(17, 2, 1, 1, 1, 2, 1, 6, 1, 5, 3, 1)
(18, 2, 1, 1, 1, 2, 2, 7, 1, 4, 8, 3)
(19, 3, 1, 1, 1, 3, 1, 7, 1, 5, 8, 1)
(20, 2, 1, 1, 1, 2, 1, 3, 1, 5, 2, 2)
(21, 2, 1, 1, 1, 2, 2, 6, 1, 4, 4, 3)
(22, 3, 1, 1, 1, 3, 2, 7, 1, 5, 9, 1)
(23, 3, 1, 1, 1, 3, 2, 7, 1, 5, 5, 1)
(24, 2, 1, 1, 1, 1, 1, 5, 1, 5, 4, 2)
(25, 2, 1, 1, 1, 1, 1, 7, 1, 4, 3, 1)
(26, 2, 1, 1, 1, 1, 1, 6, 1, 4, 3, 1)
(27, 1, 1, 1, 1, 1, 1, 5, 1, 4, 1, 1)
(28, 2, 1, 1, 1, 1, 1, 5, 1, 5, 1, 1)
(29, 2, 1, 1, 1, 2, 1, 6, 1, 5, 4, 5)
(30, 3, 1, 1, 1, 2, 1, 5, 1, 5, 4, 1)
(31, 2, 1, 1, 1, 1, 1, 5, 1, 3, 1, 3)
(32, 2, 1, 1, 1, 2, 1, 7, 1, 5, 10, 1)
(33, 3, 1, 1, 1, 3, 1, 5, 1, 5, 2, 1)
(34, 2, 3, 3, 1, 1, 1, 7, 1, 4, 7, 3)
(35, 2, 1, 1, 1, 2, 1, 5, 1, 5, 2, 5)
(36, 3, 1, 1, 1, 3, 2, 9, 1, 5, 10, 1)
(37, 2, 1, 1, 1, 1, 1, 7, 1, 4, 10, 1)
(38, 2, 1, 1, 1, 1, 1, 7, 1, 4, 4, 1)
(39, 3, 3, 3, 1, 1, 1, 8, 1, 4, 9, 1)
(40, 2, 1, 1, 1, 2, 2, 7, 1, 4, 7, 1)
(41, 2, 3, 3, 1, 2, 1, 7, 1, 5, 9, 1)
(42, 3, 1, 1, 1, 3, 2, 5, 3, 5, 6, 3)
(43, 3, 1, 1, 1, 2, 2, 5, 1, 5, 1, 3)
(44, 2, 1, 1, 1, 1, 1, 7, 1, 5, 8, 1)
(45, 1, 1, 1, 1, 1, 1, 7, 1, 3, 5, 1)
(46, 2, 1, 1, 1, 2, 2, 9, 1, 3, 9, 1)
(47, 2, 1, 1, 1, 3, 1, 7, 1, 5, 6, 8)
(48, 2, 1, 1, 1, 1, 1, 7, 1, 3, 9, 3)
(49, 2, 1, 1, 1, 2, 1, 6, 1, 5, 5, 1)
(50, 4, 1, 1, 2, 3, 3, 6, 1, 5, 3, 3)
(51, 2, 1, 1, 1, 2, 1, 5, 1, 5, 1, 1)
(52, 3, 1, 1, 1, 2, 1, 7, 1, 5, 7, 1)
(53, 2, 1, 1, 1, 2, 2, 6, 1, 5, 5, 1)
(54, 2, 1, 1, 1, 2, 1, 7, 1, 4, 8, 1)
(55, 2, 1, 1, 1, 3, 1, 5, 1, 5, 1, 1)
(56, 2, 1, 1, 1, 3, 2, 7, 1, 5, 9, 2)
(57, 2, 1, 1, 1, 1, 1, 6, 1, 4, 7, 3)
(58, 2, 1, 1, 1, 2, 2, 5, 1, 5, 3, 2)
(59, 2, 1, 2, 1, 1, 1, 5, 1, 4, 4, 2)
(60, 3, 1, 5, 1, 1, 1, 8, 1, 5, 7, 5)
(61, 2, 1, 1, 1, 2, 2, 6, 1, 5, 8, 1)
(62, 3, 1, 1, 1, 1, 2, 6, 1, 5, 3, 3)
(63, 2, 1, 1, 1, 1, 1, 6, 1, 2, 3, 3)
(64, 3, 1, 1, 1, 2, 1, 8, 1, 5, 6, 2)
(65, 3, 1, 1, 1, 3, 2, 7, 1, 5, 8, 3)
(66, 2, 1, 1, 1, 2, 1, 5, 1, 4, 4, 1)
(67, 3, 1, 3, 2, 1, 1, 5, 1, 3, 5, 3)
(68, 2, 1, 1, 1, 2, 1, 5, 1, 4, 2, 2)
(69, 3, 1, 1, 2, 1, 1, 7, 3, 5, 9, 3)
(70, 2, 1, 1, 2, 1, 1, 6, 1, 5, 4, 3)
(71, 2, 1, 1, 1, 1, 2, 7, 1, 4, 4, 2)
(72, 2, 1, 1, 1, 1, 1, 6, 1, 4, 2, 3)
(73, 2, 1, 1, 1, 1, 1, 6, 1, 4, 4, 5)
(74, 3, 1, 1, 2, 3, 3, 7, 1, 5, 10, 3)
(75, 2, 1, 1, 1, 1, 2, 9, 1, 3, 8, 1)
(76, 2, 1, 1, 1, 1, 1, 5, 1, 4, 5, 3)
(77, 2, 1, 1, 1, 1, 1, 6, 1, 5, 4, 1)
(78, 2, 1, 1, 2, 3, 3, 6, 1, 3, 1, 2)
(79, 1, 1, 1, 1, 1, 2, 7, 1, 4, 10, 1)
(80, 3, 4, 4, 1, 3, 1, 5, 1, 5, 7, 3)
(81, 2, 1, 1, 1, 2, 1, 7, 1, 3, 4, 2)
(82, 2, 1, 1, 1, 3, 1, 6, 1, 5, 7, 3)
(83, 2, 1, 1, 1, 3, 1, 7, 1, 5, 9, 8)
(84, 2, 1, 1, 1, 2, 1, 7, 1, 5, 9, 5)
(85, 1, 1, 1, 1, 1, 1, 7, 1, 2, 8, 8)
(86, 2, 1, 1, 2, 1, 2, 9, 1, 4, 10, 2)
(87, 2, 1, 1, 1, 3, 1, 5, 1, 5, 2, 3)
(88, 2, 1, 1, 1, 2, 1, 5, 1, 5, 5, 2)
(89, 3, 1, 1, 1, 2, 1, 8, 1, 5, 7, 2)
(90, 3, 1, 1, 1, 3, 2, 5, 1, 5, 2, 2)
(91, 2, 1, 1, 1, 2, 1, 9, 1, 3, 10, 1)
(92, 2, 1, 1, 1, 2, 2, 7, 1, 5, 6, 1)
(93, 3, 1, 1, 1, 3, 2, 7, 1, 5, 4, 1)
(94, 2, 1, 1, 1, 1, 1, 7, 1, 4, 7, 1)
(95, 3, 1, 1, 1, 3, 3, 7, 1, 5, 10, 1)
(96, 2, 1, 1, 1, 1, 1, 5, 1, 5, 4, 1)
(97, 2, 1, 1, 1, 1, 2, 6, 1, 4, 3, 1)
(98, 3, 1, 1, 1, 3, 1, 4, 1, 5, 3, 1)
(99, 2, 1, 1, 1, 2, 1, 5, 1, 5, 10, 1)
(100, 2, 1, 1, 1, 2, 1, 6, 1, 5, 7, 1)
(101, 2, 1, 1, 1, 1, 1, 5, 1, 4, 1, 1)
(102, 2, 1, 1, 1, 3, 1, 6, 1, 2, 2, 1)
(103, 3, 3, 3, 1, 1, 1, 6, 1, 5, 5, 1)
(104, 2, 1, 1, 1, 1, 2, 6, 1, 5, 3, 1)
(105, 2, 1, 1, 1, 1, 1, 7, 1, 5, 5, 1)
(106, 2, 1, 1, 2, 2, 2, 6, 1, 5, 8, 1)
(107, 2, 1, 1, 1, 1, 1, 6, 1, 4, 5, 1)
(108, 3, 1, 1, 2, 1, 3, 5, 1, 5, 2, 1)
(109, 2, 1, 1, 1, 1, 1, 7, 1, 2, 10, 1)
(110, 2, 1, 1, 1, 2, 2, 7, 1, 5, 9, 1)
(111, 2, 1, 1, 1, 1, 1, 6, 1, 4, 7, 1)
(112, 2, 1, 1, 1, 2, 1, 8, 1, 4, 8, 1)
(113, 2, 1, 1, 1, 1, 1, 6, 1, 2, 2, 1)
(114, 2, 1, 1, 1, 2, 1, 6, 1, 4, 5, 1)
(115, 1, 1, 1, 1, 1, 1, 2, 1, 4, 3, 1)
(116, 2, 1, 1, 1, 3, 1, 6, 1, 5, 10, 1)
(117, 2, 1, 1, 1, 2, 1, 6, 1, 5, 3, 1)
(118, 2, 2, 2, 1, 2, 1, 7, 1, 5, 7, 1)
(119, 2, 1, 1, 1, 3, 1, 9, 1, 5, 9, 1)
(120, 2, 1, 1, 1, 1, 1, 8, 1, 3, 5, 1)
(121, 3, 4, 4, 1, 3, 1, 8, 1, 5, 9, 1)
(122, 3, 1, 1, 1, 2, 1, 6, 1, 5, 4, 1)
(123, 2, 1, 1, 1, 2, 2, 6, 1, 5, 6, 1)
(124, 3, 3, 3, 1, 3, 1, 5, 1, 5, 4, 1)
(125, 2, 1, 1, 1, 1, 1, 6, 1, 5, 5, 1)
(126, 3, 1, 1, 2, 1, 1, 5, 1, 5, 4, 1)
(127, 2, 1, 1, 1, 1, 1, 7, 1, 4, 6, 1)
(128, 3, 3, 3, 1, 2, 2, 9, 1, 5, 7, 2)
(129, 3, 1, 1, 1, 3, 2, 5, 1, 5, 4, 1)
(130, 3, 1, 1, 1, 3, 1, 7, 1, 5, 6, 1)
(131, 2, 1, 5, 1, 2, 2, 5, 1, 5, 1, 1)
(132, 1, 1, 1, 1, 2, 1, 4, 1, 5, 1, 1)
(133, 2, 1, 1, 1, 3, 3, 5, 1, 5, 2, 1)
(134, 2, 4, 4, 1, 3, 2, 7, 1, 5, 9, 1)
(135, 2, 1, 1, 1, 1, 2, 6, 1, 5, 6, 1)
(136, 2, 1, 1, 1, 3, 1, 5, 1, 5, 5, 1)
(137, 3, 1, 3, 2, 1, 2, 5, 1, 5, 3, 1)
(138, 2, 1, 1, 1, 3, 2, 6, 1, 5, 6, 1)
(139, 2, 1, 1, 1, 2, 1, 8, 1, 5, 8, 1)
(140, 2, 1, 1, 1, 1, 1, 6, 1, 4, 6, 3)
(141, 2, 1, 1, 1, 1, 1, 9, 1, 4, 10, 1)
(142, 2, 1, 1, 1, 3, 1, 6, 1, 5, 4, 8)
(143, 2, 1, 1, 1, 3, 2, 5, 1, 5, 4, 1)
(144, 3, 1, 1, 1, 3, 2, 7, 1, 5, 8, 1)
(145, 2, 1, 1, 1, 2, 1, 6, 1, 5, 4, 1)
(146, 2, 1, 1, 1, 1, 1, 7, 1, 4, 3, 1)
(147, 3, 1, 1, 1, 2, 2, 7, 1, 5, 7, 1)
(148, 2, 1, 1, 1, 2, 1, 6, 1, 1, 4, 8)
(149, 2, 1, 1, 1, 2, 2, 6, 1, 5, 7, 1)
(150, 2, 1, 1, 1, 2, 1, 6, 1, 2, 6, 2)
(151, 3, 1, 1, 1, 2, 1, 5, 2, 5, 1, 1)
(152, 2, 1, 1, 1, 2, 1, 5, 1, 5, 2, 1)
(153, 1, 1, 1, 2, 1, 2, 5, 1, 3, 6, 1)
(154, 2, 1, 1, 1, 2, 1, 6, 1, 5, 7, 1)
(155, 2, 3, 3, 1, 2, 1, 6, 1, 5, 3, 2)
(156, 3, 1, 1, 2, 2, 2, 5, 1, 5, 5, 1)
(157, 2, 1, 1, 1, 1, 1, 6, 1, 4, 5, 1)
(158, 2, 1, 1, 1, 2, 1, 7, 1, 4, 4, 1)
(159, 2, 1, 1, 2, 1, 2, 6, 1, 4, 6, 3)
(160, 3, 1, 1, 1, 3, 2, 5, 1, 5, 5, 3)
(161, 3, 1, 1, 2, 3, 3, 4, 1, 5, 6, 1)
(162, 3, 1, 1, 1, 3, 1, 5, 2, 5, 6, 1)
(163, 2, 1, 1, 1, 2, 1, 5, 1, 5, 5, 8)
(164, 1, 1, 1, 1, 1, 1, 6, 1, 4, 2, 2)
(165, 3, 1, 1, 1, 3, 1, 5, 1, 5, 5, 1)
(166, 2, 1, 1, 1, 1, 1, 6, 1, 4, 6, 3)
(167, 3, 1, 1, 1, 3, 1, 7, 1, 5, 9, 1)
(168, 2, 1, 2, 1, 3, 2, 4, 1, 5, 5, 5)
(169, 2, 1, 1, 1, 3, 2, 7, 1, 5, 8, 1)
(170, 3, 1, 1, 1, 2, 1, 6, 1, 5, 6, 3)
(171, 2, 1, 1, 1, 2, 1, 7, 1, 5, 9, 5)
(172, 2, 1, 1, 2, 1, 1, 6, 1, 5, 10, 5)
(173, 2, 1, 1, 1, 1, 1, 6, 2, 3, 8, 8)
(174, 2, 1, 1, 1, 2, 2, 7, 1, 5, 9, 3)
(175, 3, 1, 1, 1, 3, 1, 7, 1, 5, 8, 3)
(176, 2, 1, 1, 1, 2, 1, 3, 1, 4, 1, 1)
(177, 2, 1, 1, 1, 2, 1, 6, 1, 5, 6, 1)
(178, 2, 1, 1, 1, 2, 2, 6, 1, 2, 1, 1)
(179, 3, 1, 1, 1, 3, 2, 7, 1, 5, 8, 1)
(180, 2, 1, 1, 1, 1, 1, 7, 1, 3, 5, 1)
(181, 3, 1, 1, 1, 3, 1, 5, 1, 5, 5, 1)
(182, 2, 1, 1, 1, 3, 2, 6, 1, 5, 5, 3)
(183, 1, 1, 1, 1, 1, 1, 6, 1, 3, 3, 5)
(184, 2, 1, 1, 1, 2, 1, 7, 1, 1, 4, 8)
(185, 2, 1, 1, 1, 2, 1, 5, 1, 5, 5, 8)
(186, 2, 1, 1, 1, 3, 1, 8, 1, 5, 9, 2)
(187, 3, 1, 1, 1, 3, 2, 7, 1, 5, 9, 5)
(188, 2, 1, 1, 1, 2, 2, 7, 1, 5, 8, 1)
(189, 2, 1, 1, 1, 3, 1, 6, 1, 5, 2, 1)
(190, 2, 1, 1, 1, 3, 3, 6, 1, 5, 3, 1)
(191, 2, 1, 1, 1, 2, 1, 5, 1, 5, 3, 2)
(192, 3, 1, 1, 2, 2, 1, 6, 1, 5, 8, 8)
(193, 2, 1, 1, 1, 3, 2, 5, 1, 5, 6, 1)
(194, 2, 1, 1, 1, 2, 1, 5, 1, 5, 6, 2)
(195, 2, 1, 1, 1, 2, 1, 6, 1, 5, 3, 1)
(196, 2, 1, 1, 1, 2, 1, 6, 1, 5, 8, 1)
(197, 3, 1, 1, 2, 2, 3, 7, 1, 5, 10, 1)
(198, 2, 1, 1, 1, 2, 1, 7, 3, 4, 3, 1)
(199, 2, 1, 1, 1, 1, 1, 6, 1, 5, 7, 1)
(200, 3, 1, 1, 1, 2, 2, 7, 1, 5, 10, 1)
(201, 2, 1, 1, 1, 1, 2, 5, 1, 5, 4, 2)
(202, 1, 1, 1, 1, 1, 1, 6, 1, 4, 4, 2)
(203, 2, 1, 1, 1, 2, 1, 4, 1, 5, 1, 5)
(204, 1, 1, 1, 1, 2, 1, 5, 1, 5, 3, 2)
(205, 2, 1, 1, 1, 2, 1, 5, 1, 5, 7, 2)
(206, 2, 1, 1, 1, 1, 1, 5, 1, 4, 2, 2)
(207, 3, 1, 1, 1, 3, 2, 5, 1, 5, 7, 3)
(208, 2, 1, 1, 1, 3, 2, 8, 1, 5, 5, 2)
(209, 1, 1, 1, 1, 1, 1, 5, 1, 5, 7, 8)
(210, 2, 1, 1, 1, 3, 3, 5, 1, 5, 6, 5)
(211, 2, 1, 1, 1, 2, 2, 5, 1, 5, 5, 1)
(212, 2, 1, 1, 1, 3, 1, 4, 1, 5, 4, 3)
(213, 2, 1, 1, 1, 3, 2, 7, 1, 5, 10, 1)
(214, 2, 1, 1, 1, 2, 1, 5, 1, 5, 6, 2)
(215, 2, 1, 1, 1, 1, 1, 7, 1, 3, 4, 1)
(216, 2, 1, 1, 1, 2, 2, 5, 1, 5, 5, 1)
(217, 1, 1, 1, 1, 1, 1, 5, 1, 4, 1, 1)
(218, 5, 1, 1, 2, 3, 3, 8, 3, 5, 9, 1)
(219, 2, 1, 1, 1, 3, 2, 5, 1, 5, 7, 2)
(220, 2, 1, 1, 1, 2, 1, 5, 1, 5, 6, 2)
(221, 2, 1, 1, 1, 2, 1, 6, 1, 5, 5, 3)
(222, 2, 1, 1, 1, 2, 1, 5, 1, 5, 5, 2)
(223, 2, 1, 1, 1, 1, 1, 5, 1, 5, 6, 2)
(224, 2, 1, 1, 1, 3, 2, 5, 1, 5, 8, 2)
(225, 2, 1, 1, 1, 2, 3, 7, 1, 5, 10, 1)
(226, 2, 1, 1, 1, 2, 1, 5, 1, 5, 6, 8)
(227, 1, 1, 1, 1, 1, 1, 7, 1, 4, 4, 8)
(228, 2, 1, 1, 1, 2, 1, 6, 1, 5, 6, 2)
(229, 2, 1, 1, 1, 3, 1, 4, 1, 5, 3, 2)
(230, 2, 1, 1, 1, 1, 1, 6, 1, 4, 4, 2)
(231, 2, 1, 1, 1, 2, 2, 5, 1, 5, 7, 8)
(232, 1, 1, 1, 1, 1, 1, 5, 1, 4, 1, 1)
(233, 2, 1, 1, 2, 1, 1, 7, 1, 5, 9, 1)
(234, 2, 1, 1, 2, 1, 1, 5, 1, 5, 5, 1)
(235, 2, 1, 1, 1, 1, 1, 5, 1, 5, 7, 2)
(236, 2, 1, 1, 1, 2, 1, 5, 1, 5, 2, 2)
(237, 2, 1, 1, 1, 3, 1, 7, 1, 5, 8, 1)
(238, 2, 1, 1, 1, 2, 2, 5, 1, 5, 2, 1)
(239, 2, 1, 1, 2, 1, 2, 4, 1, 5, 2, 1)
(240, 2, 1, 1, 1, 2, 2, 5, 1, 5, 2, 2)
(241, 2, 1, 1, 1, 2, 1, 5, 1, 5, 6, 5)
(242, 1, 1, 1, 1, 1, 2, 7, 1, 3, 5, 2)
(243, 1, 1, 1, 1, 1, 1, 7, 1, 4, 5, 1)
(244, 1, 1, 1, 1, 1, 1, 6, 1, 4, 1, 7)
(245, 3, 1, 1, 1, 2, 1, 5, 1, 5, 3, 3)
(246, 2, 1, 1, 1, 1, 1, 5, 1, 5, 3, 3)
(247, 2, 1, 1, 2, 1, 1, 5, 1, 3, 1, 7)
(248, 2, 1, 1, 1, 3, 1, 4, 1, 3, 3, 3)
(249, 2, 1, 1, 1, 2, 1, 4, 1, 4, 1, 8)
(250, 2, 1, 1, 1, 2, 1, 6, 1, 5, 3, 8)
(251, 2, 1, 1, 1, 3, 1, 6, 1, 5, 4, 8)
(252, 3, 1, 1, 1, 1, 1, 6, 1, 5, 5, 7)
(253, 3, 1, 1, 1, 2, 1, 6, 1, 4, 2, 4)
(254, 1, 1, 1, 1, 1, 1, 6, 1, 4, 1, 5)
(255, 1, 1, 1, 1, 1, 1, 6, 1, 3, 4, 5)
(256, 3, 1, 1, 1, 1, 1, 5, 2, 5, 2, 6)
(257, 2, 1, 1, 1, 2, 1, 6, 1, 5, 7, 3)
(258, 3, 1, 1, 2, 1, 2, 5, 1, 5, 3, 3)
(259, 1, 1, 1, 1, 1, 1, 5, 1, 3, 5, 3)
(260, 3, 1, 1, 1, 2, 1, 4, 1, 5, 1, 7)
(261, 3, 1, 1, 1, 2, 1, 6, 1, 5, 5, 8)
(262, 2, 1, 1, 1, 2, 1, 6, 1, 4, 5, 7)
(263, 2, 1, 1, 2, 1, 1, 6, 1, 5, 3, 2)
(264, 2, 1, 1, 1, 1, 1, 6, 1, 4, 5, 7)
(265, 2, 1, 1, 1, 2, 1, 6, 1, 5, 4, 2)
(266, 1, 1, 1, 1, 1, 1, 6, 1, 3, 1, 2)
(267, 3, 1, 1, 1, 3, 1, 5, 1, 3, 2, 8)
(268, 2, 1, 1, 1, 1, 1, 6, 1, 4, 4, 2)
(269, 2, 1, 1, 1, 2, 1, 6, 1, 4, 2, 8)
(270, 1, 1, 1, 1, 1, 1, 7, 1, 3, 5, 2)
(271, 2, 1, 1, 1, 2, 1, 6, 1, 4, 6, 2)
(272, 3, 1, 1, 1, 3, 1, 8, 1, 5, 6, 8)
(273, 2, 1, 1, 1, 2, 1, 6, 1, 3, 2, 8)
(274, 2, 1, 1, 1, 3, 1, 6, 1, 5, 3, 2)
(275, 2, 1, 1, 1, 2, 1, 7, 1, 5, 5, 2)
(276, 2, 1, 1, 1, 1, 1, 5, 1, 4, 2, 8)
(277, 2, 1, 1, 1, 2, 1, 5, 1, 2, 8, 8)
(278, 4, 1, 1, 2, 3, 1, 4, 1, 5, 2, 8)
(279, 2, 1, 1, 1, 1, 1, 5, 1, 1, 2, 8)
(280, 2, 1, 1, 1, 3, 2, 9, 1, 4, 8, 5)
(281, 2, 1, 1, 1, 1, 1, 6, 1, 4, 1, 8)
(282, 2, 1, 1, 1, 2, 1, 5, 1, 5, 2, 3)
(283, 2, 1, 1, 1, 3, 1, 6, 1, 5, 3, 5)
(284, 3, 1, 1, 2, 3, 1, 5, 1, 5, 5, 3)
(285, 2, 1, 1, 1, 1, 1, 7, 1, 4, 6, 5)
(286, 2, 1, 1, 1, 1, 1, 6, 1, 5, 4, 2)
(287, 3, 1, 1, 1, 3, 2, 9, 2, 2, 6, 7)
(288, 1, 1, 1, 1, 1, 1, 6, 1, 1, 2, 5)
(289, 1, 1, 1, 1, 1, 1, 5, 1, 3, 5, 8)
(290, 2, 1, 1, 1, 2, 1, 4, 1, 3, 6, 8)
(291, 4, 1, 1, 1, 3, 1, 5, 1, 4, 2, 8)
(292, 2, 1, 1, 1, 1, 1, 8, 1, 4, 9, 5)
(293, 2, 1, 1, 1, 1, 1, 5, 1, 5, 5, 5)
(294, 2, 1, 1, 1, 1, 1, 7, 1, 4, 3, 3)
(295, 2, 1, 1, 1, 2, 1, 5, 1, 4, 4, 3)
(296, 2, 1, 1, 1, 2, 1, 9, 1, 4, 9, 1)
(297, 2, 1, 1, 1, 1, 1, 5, 1, 5, 5, 1)
(298, 3, 1, 1, 1, 3, 1, 7, 1, 5, 8, 8)
(299, 2, 1, 1, 1, 2, 1, 7, 1, 2, 6, 5)
(300, 2, 1, 1, 1, 1, 2, 7, 1, 5, 9, 2)
(301, 1, 1, 1, 1, 2, 1, 6, 1, 4, 2, 2)
(302, 2, 1, 1, 1, 2, 1, 7, 1, 5, 2, 1)
(303, 2, 1, 1, 1, 2, 1, 4, 1, 5, 4, 1)
(304, 2, 1, 1, 1, 3, 3, 6, 1, 5, 6, 1)
(305, 4, 1, 1, 2, 2, 2, 6, 1, 5, 7, 3)
(306, 2, 1, 1, 1, 2, 2, 9, 1, 5, 8, 1)
(307, 2, 1, 1, 1, 3, 1, 6, 1, 5, 2, 1)
(308, 3, 1, 1, 2, 1, 3, 5, 1, 5, 2, 1)
(309, 2, 1, 1, 1, 2, 1, 6, 1, 5, 6, 1)

In [4]:
import pandas as pd
from sqlalchemy import create_engine, text

# Create engine to male_fertility.sqlite
file_path = "/content/drive/MyDrive/Colab Notebooks/male_fertility.sqlite"
engine = create_engine(f"sqlite:///{file_path}")

# Define your SQL query
query = text("SELECT * FROM male_sperm")

# Execute the query and load data into a DataFrame
with engine.connect() as connection:
    result = connection.execute(query)
    # Fetch all rows into a list of tuples
    rows = result.fetchall()

# Get the column names from the result set
columns = result.keys()

# Create a DataFrame from the rows and columns
male_sperm = pd.DataFrame(rows, columns=columns)

# Print the DataFrame
print(male_sperm)

      ID  Age  Religion  Ethnicity  Maritalstatus  Marriageperiod  \
0      1    2         1          1              1               1
1      2    2         1          1              1               2
2      3    2         1          1              1               2
3      4    3         1          1              2               1
4      5    2         1          1              1               1
..   ...  ...       ...        ...            ...             ...
304  305    4         1          1              2               2
305  306    2         1          1              1               2
306  307    2         1          1              1               3
307  308    3         1          1              2               1
308  309    2         1          1              1               2

     No.ofchildren  Educationallevel  Employmentstatus  Workingperiod  \
0                1                 6                 1              4
1                1                 6                 1              3
2                1                 6                 1              5
3                2                 5                 1              5
4                1                 6                 1              3
..             ...               ...               ...            ...
304              2                 6                 1              5
305              2                 9                 1              5
306              1                 6                 1              5
307              3                 5                 1              5
308              1                 6                 1              5

     Householdincome  Spermquality
0                  7             3
1                  4             1
2                  7             1
3                 10             1
4                  5             1
..               ...           ...
304                7             3
305                8             1
306                2             1
307                2             1
308                6             1

[309 rows x 12 columns]

In [5]:
male_sperm = male_sperm.drop(columns = ['Religion'], axis =1)
male_sperm

,ID,Age,Ethnicity,Maritalstatus,Marriageperiod,No.ofchildren,Educationallevel,Employmentstatus,Workingperiod,Householdincome,Spermquality
0,1,2,1,1,1,1,6,1,4,7,3
1,2,2,1,1,2,1,6,1,3,4,1
2,3,2,1,1,2,1,6,1,5,7,1
3,4,3,1,2,1,2,5,1,5,10,1
4,5,2,1,1,1,1,6,1,3,5,1
...,...,...,...,...,...,...,...,...,...,...,...
304,305,4,1,2,2,2,6,1,5,7,3
305,306,2,1,1,2,2,9,1,5,8,1
306,307,2,1,1,3,1,6,1,5,2,1
307,308,3,1,2,1,3,5,1,5,2,1
308,309,2,1,1,2,1,6,1,5,6,1

In [6]:
# Determine the number of unique values in each column.
for x in male_sperm.columns:
    print(x,len(male_sperm[x].unique()))

ID 309
Age 5
Ethnicity 5
Maritalstatus 2
Marriageperiod 3
No.ofchildren 3
Educationallevel 8
Employmentstatus 3
Workingperiod 5
Householdincome 10
Spermquality 8

In [7]:
counts = male_sperm['Spermquality'].value_counts()
counts

1    144
2     52
3     48
8     31
5     24
7      8
4      1
6      1
Name: Spermquality, dtype: int64

In [8]:
# Choose a cutoff value and create a list of Age types to be replaced
# use the variable name `Age_types_to_replace`
Age_types_to_replace = list(counts[counts<10].index)

# Replace in dataframe
for app in Age_types_to_replace:
    male_sperm['Spermquality'] = male_sperm['Spermquality'].replace(app,"Other")

# Check to make sure binning was successful
male_sperm['Spermquality'].value_counts()

1        144
2         52
3         48
8         31
5         24
Other     10
Name: Spermquality, dtype: int64

In [28]:
countsbinning = male_sperm['Householdincome'].value_counts()
countsbinning

5     46
4     39
6     38
2     35
3     31
7     28
1     26
8     25
9     23
10    18
Name: Householdincome, dtype: int64

In [10]:
# # Choose a cutoff value and create a list of classifications to be replaced
# # use the variable name `classifications_to_replace`
# classifications_to_replace = list (countsbinning[countsbinning<20].index)

# # Replace in dataframe
# for cls in classifications_to_replace:
#     male_sperm['Workingperiod'] = male_sperm['Workingperiod'].replace(cls,"Other")

# # Check to make sure binning was successful
# male_sperm['Workingperiod'].value_counts()

5        194
4         73
3         28
Other     14
Name: Workingperiod, dtype: int64

In [29]:
male_sperm = pd.get_dummies(male_sperm, dtype=float)
male_sperm.head()

,ID,Age,Ethnicity,Maritalstatus,Marriageperiod,No.ofchildren,Educationallevel,Employmentstatus,Workingperiod,Householdincome,Spermquality_1,Spermquality_2,Spermquality_3,Spermquality_5,Spermquality_8,Spermquality_Other
0,1,2,1,1,1,1,6,1,4,7,0.0,0.0,1.0,0.0,0.0,0.0
1,2,2,1,1,2,1,6,1,3,4,1.0,0.0,0.0,0.0,0.0,0.0
2,3,2,1,1,2,1,6,1,5,7,1.0,0.0,0.0,0.0,0.0,0.0
3,4,3,1,2,1,2,5,1,5,10,1.0,0.0,0.0,0.0,0.0,0.0
4,5,2,1,1,1,1,6,1,3,5,1.0,0.0,0.0,0.0,0.0,0.0

In [30]:
y = male_sperm['No.ofchildren'].values
y

array([1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1,
       1, 2, 1, 1, 1, 3, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 1,
       1, 1, 1, 1, 2, 1, 1, 3, 2, 1, 1, 3, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 2, 1, 2, 2, 1, 3, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 3, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1,
       3, 2, 2, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1,
       1, 2, 1, 1, 2, 2, 3, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1,
       1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 3, 1, 1, 2, 1, 1, 1, 3, 1,
       1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 3, 2, 1, 2, 1, 1, 2, 1, 3, 2, 1,
       1, 1, 1, 2, 3, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 3, 2, 2, 1, 3,
       1])

In [31]:
X = male_sperm.drop('No.ofchildren', axis =1).values
X

array([[  1.,   2.,   1., ...,   0.,   0.,   0.],
       [  2.,   2.,   1., ...,   0.,   0.,   0.],
       [  3.,   2.,   1., ...,   0.,   0.,   0.],
       ...,
       [307.,   2.,   1., ...,   0.,   0.,   0.],
       [308.,   3.,   1., ...,   0.,   0.,   0.],
       [309.,   2.,   1., ...,   0.,   0.,   0.]])

In [32]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 42)

In [33]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [38]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = len(X_train_scaled[0])
first_hidden_layer = 20
second_hidden_layer = 20
third_hidden_layer = 8

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=first_hidden_layer, input_dim = input_features, activation='relu'))
# Second hidden layer
nn.add(tf.keras.layers.Dense(units=second_hidden_layer, activation = 'relu'))
# Third hidden layer
nn.add(tf.keras.layers.Dense(units=third_hidden_layer, activation = 'relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1,activation = 'sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 20)                320

 dense_13 (Dense)            (None, 20)                420

 dense_14 (Dense)            (None, 8)                 168

 dense_15 (Dense)            (None, 1)                 9

=================================================================
Total params: 917 (3.58 KB)
Trainable params: 917 (3.58 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [39]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [40]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train,validation_split = 0.15, epochs=100)

Epoch 1/100
7/7 [==============================] - 1s 41ms/step - loss: 1.1894 - accuracy: 0.0051 - val_loss: 1.1613 - val_accuracy: 0.0286
Epoch 2/100
7/7 [==============================] - 0s 8ms/step - loss: 1.0281 - accuracy: 0.0408 - val_loss: 1.0085 - val_accuracy: 0.0857
Epoch 3/100
7/7 [==============================] - 0s 7ms/step - loss: 0.9132 - accuracy: 0.1224 - val_loss: 0.8859 - val_accuracy: 0.2000
Epoch 4/100
7/7 [==============================] - 0s 7ms/step - loss: 0.8199 - accuracy: 0.2755 - val_loss: 0.7860 - val_accuracy: 0.3143
Epoch 5/100
7/7 [==============================] - 0s 10ms/step - loss: 0.7445 - accuracy: 0.4439 - val_loss: 0.7021 - val_accuracy: 0.5143
Epoch 6/100
7/7 [==============================] - 0s 11ms/step - loss: 0.6754 - accuracy: 0.5561 - val_loss: 0.6287 - val_accuracy: 0.6286
Epoch 7/100
7/7 [==============================] - 0s 11ms/step - loss: 0.6113 - accuracy: 0.6378 - val_loss: 0.5634 - val_accuracy: 0.6857
Epoch 8/100
7/7 [==============================] - 0s 11ms/step - loss: 0.5470 - accuracy: 0.6888 - val_loss: 0.4970 - val_accuracy: 0.6857
Epoch 9/100
7/7 [==============================] - 0s 8ms/step - loss: 0.4831 - accuracy: 0.7092 - val_loss: 0.4257 - val_accuracy: 0.7143
Epoch 10/100
7/7 [==============================] - 0s 11ms/step - loss: 0.4147 - accuracy: 0.7296 - val_loss: 0.3496 - val_accuracy: 0.7143
Epoch 11/100
7/7 [==============================] - 0s 10ms/step - loss: 0.3421 - accuracy: 0.7449 - val_loss: 0.2649 - val_accuracy: 0.7143
Epoch 12/100
7/7 [==============================] - 0s 11ms/step - loss: 0.2641 - accuracy: 0.7449 - val_loss: 0.1667 - val_accuracy: 0.7143
Epoch 13/100
7/7 [==============================] - 0s 9ms/step - loss: 0.1759 - accuracy: 0.7449 - val_loss: 0.0569 - val_accuracy: 0.7143
Epoch 14/100
7/7 [==============================] - 0s 10ms/step - loss: 0.0688 - accuracy: 0.7449 - val_loss: -0.0620 - val_accuracy: 0.7143
Epoch 15/100
7/7 [==============================] - 0s 8ms/step - loss: -0.0423 - accuracy: 0.7449 - val_loss: -0.1945 - val_accuracy: 0.7143
Epoch 16/100
7/7 [==============================] - 0s 8ms/step - loss: -0.1670 - accuracy: 0.7449 - val_loss: -0.3475 - val_accuracy: 0.7143
Epoch 17/100
7/7 [==============================] - 0s 12ms/step - loss: -0.3055 - accuracy: 0.7449 - val_loss: -0.5143 - val_accuracy: 0.7143
Epoch 18/100
7/7 [==============================] - 0s 9ms/step - loss: -0.4579 - accuracy: 0.7449 - val_loss: -0.6916 - val_accuracy: 0.7143
Epoch 19/100
7/7 [==============================] - 0s 12ms/step - loss: -0.6142 - accuracy: 0.7449 - val_loss: -0.8880 - val_accuracy: 0.7143
Epoch 20/100
7/7 [==============================] - 0s 8ms/step - loss: -0.7714 - accuracy: 0.7449 - val_loss: -1.1125 - val_accuracy: 0.7143
Epoch 21/100
7/7 [==============================] - 0s 13ms/step - loss: -0.9534 - accuracy: 0.7449 - val_loss: -1.3313 - val_accuracy: 0.7143
Epoch 22/100
7/7 [==============================] - 0s 9ms/step - loss: -1.1261 - accuracy: 0.7449 - val_loss: -1.5796 - val_accuracy: 0.7143
Epoch 23/100
7/7 [==============================] - 0s 14ms/step - loss: -1.3342 - accuracy: 0.7449 - val_loss: -1.8287 - val_accuracy: 0.7143
Epoch 24/100
7/7 [==============================] - 0s 13ms/step - loss: -1.5488 - accuracy: 0.7449 - val_loss: -2.1335 - val_accuracy: 0.7143
Epoch 25/100
7/7 [==============================] - 0s 9ms/step - loss: -1.8104 - accuracy: 0.7449 - val_loss: -2.4956 - val_accuracy: 0.7143
Epoch 26/100
7/7 [==============================] - 0s 9ms/step - loss: -2.1045 - accuracy: 0.7449 - val_loss: -2.8965 - val_accuracy: 0.7143
Epoch 27/100
7/7 [==============================] - 0s 12ms/step - loss: -2.4357 - accuracy: 0.7449 - val_loss: -3.3423 - val_accuracy: 0.7143
Epoch 28/100
7/7 [==============================] - 0s 11ms/step - loss: -2.8256 - accuracy: 0.7449 - val_loss: -3.8550 - val_accuracy: 0.7143
Epoch 29/100
7/7 [==============================] - 0s 11ms/step - loss: -3.2560 - accuracy: 0.7449 - val_loss: -4.4631 - val_accuracy: 0.7143
Epoch 30/100
7/7 [==============================] - 0s 9ms/step - loss: -3.8040 - accuracy: 0.7449 - val_loss: -5.1795 - val_accuracy: 0.7143
Epoch 31/100
7/7 [==============================] - 0s 8ms/step - loss: -4.4180 - accuracy: 0.7449 - val_loss: -6.0213 - val_accuracy: 0.7143
Epoch 32/100
7/7 [==============================] - 0s 11ms/step - loss: -5.1184 - accuracy: 0.7449 - val_loss: -7.0403 - val_accuracy: 0.7143
Epoch 33/100
7/7 [==============================] - 0s 11ms/step - loss: -5.9481 - accuracy: 0.7449 - val_loss: -8.1436 - val_accuracy: 0.7143
Epoch 34/100
7/7 [==============================] - 0s 9ms/step - loss: -6.9046 - accuracy: 0.7449 - val_loss: -9.3112 - val_accuracy: 0.7143
Epoch 35/100
7/7 [==============================] - 0s 11ms/step - loss: -7.8954 - accuracy: 0.7449 - val_loss: -10.6523 - val_accuracy: 0.7143
Epoch 36/100
7/7 [==============================] - 0s 8ms/step - loss: -8.9695 - accuracy: 0.7449 - val_loss: -12.3753 - val_accuracy: 0.7143
Epoch 37/100
7/7 [==============================] - 0s 7ms/step - loss: -10.3065 - accuracy: 0.7449 - val_loss: -14.3057 - val_accuracy: 0.7143
Epoch 38/100
7/7 [==============================] - 0s 8ms/step - loss: -11.9046 - accuracy: 0.7449 - val_loss: -16.4118 - val_accuracy: 0.7143
Epoch 39/100
7/7 [==============================] - 0s 10ms/step - loss: -13.5841 - accuracy: 0.7449 - val_loss: -18.6816 - val_accuracy: 0.7143
Epoch 40/100
7/7 [==============================] - 0s 11ms/step - loss: -15.4224 - accuracy: 0.7449 - val_loss: -21.2231 - val_accuracy: 0.7143
Epoch 41/100
7/7 [==============================] - 0s 11ms/step - loss: -17.4146 - accuracy: 0.7449 - val_loss: -24.0824 - val_accuracy: 0.7143
Epoch 42/100
7/7 [==============================] - 0s 8ms/step - loss: -19.7845 - accuracy: 0.7449 - val_loss: -27.2073 - val_accuracy: 0.7143
Epoch 43/100
7/7 [==============================] - 0s 10ms/step - loss: -22.3061 - accuracy: 0.7449 - val_loss: -30.8333 - val_accuracy: 0.7143
Epoch 44/100
7/7 [==============================] - 0s 10ms/step - loss: -25.2466 - accuracy: 0.7449 - val_loss: -35.2057 - val_accuracy: 0.7143
Epoch 45/100
7/7 [==============================] - 0s 8ms/step - loss: -28.8321 - accuracy: 0.7449 - val_loss: -40.1911 - val_accuracy: 0.7143
Epoch 46/100
7/7 [==============================] - 0s 8ms/step - loss: -32.8236 - accuracy: 0.7449 - val_loss: -45.7566 - val_accuracy: 0.7143
Epoch 47/100
7/7 [==============================] - 0s 10ms/step - loss: -36.9895 - accuracy: 0.7449 - val_loss: -51.4915 - val_accuracy: 0.7143
Epoch 48/100
7/7 [==============================] - 0s 8ms/step - loss: -41.3072 - accuracy: 0.7449 - val_loss: -57.6637 - val_accuracy: 0.7143
Epoch 49/100
7/7 [==============================] - 0s 10ms/step - loss: -46.4876 - accuracy: 0.7449 - val_loss: -64.3495 - val_accuracy: 0.7143
Epoch 50/100
7/7 [==============================] - 0s 11ms/step - loss: -51.6437 - accuracy: 0.7449 - val_loss: -72.1039 - val_accuracy: 0.7143
Epoch 51/100
7/7 [==============================] - 0s 12ms/step - loss: -57.7987 - accuracy: 0.7449 - val_loss: -80.0755 - val_accuracy: 0.7143
Epoch 52/100
7/7 [==============================] - 0s 10ms/step - loss: -63.6749 - accuracy: 0.7449 - val_loss: -88.9476 - val_accuracy: 0.7143
Epoch 53/100
7/7 [==============================] - 0s 11ms/step - loss: -70.9080 - accuracy: 0.7449 - val_loss: -98.4423 - val_accuracy: 0.7143
Epoch 54/100
7/7 [==============================] - 0s 9ms/step - loss: -78.2826 - accuracy: 0.7449 - val_loss: -108.5992 - val_accuracy: 0.7143
Epoch 55/100
7/7 [==============================] - 0s 9ms/step - loss: -86.2219 - accuracy: 0.7449 - val_loss: -119.4601 - val_accuracy: 0.7143
Epoch 56/100
7/7 [==============================] - 0s 11ms/step - loss: -94.9192 - accuracy: 0.7449 - val_loss: -131.1856 - val_accuracy: 0.7143
Epoch 57/100
7/7 [==============================] - 0s 9ms/step - loss: -104.6534 - accuracy: 0.7449 - val_loss: -144.3853 - val_accuracy: 0.7143
Epoch 58/100
7/7 [==============================] - 0s 12ms/step - loss: -114.9128 - accuracy: 0.7449 - val_loss: -158.9166 - val_accuracy: 0.7143
Epoch 59/100
7/7 [==============================] - 0s 12ms/step - loss: -126.9593 - accuracy: 0.7449 - val_loss: -175.1345 - val_accuracy: 0.7143
Epoch 60/100
7/7 [==============================] - 0s 9ms/step - loss: -138.7511 - accuracy: 0.7449 - val_loss: -191.6499 - val_accuracy: 0.7143
Epoch 61/100
7/7 [==============================] - 0s 9ms/step - loss: -151.4465 - accuracy: 0.7449 - val_loss: -209.1298 - val_accuracy: 0.7143
Epoch 62/100
7/7 [==============================] - 0s 10ms/step - loss: -165.6503 - accuracy: 0.7449 - val_loss: -226.5221 - val_accuracy: 0.7143
Epoch 63/100
7/7 [==============================] - 0s 12ms/step - loss: -179.6230 - accuracy: 0.7449 - val_loss: -245.1538 - val_accuracy: 0.7143
Epoch 64/100
7/7 [==============================] - 0s 11ms/step - loss: -193.4846 - accuracy: 0.7449 - val_loss: -266.9533 - val_accuracy: 0.7143
Epoch 65/100
7/7 [==============================] - 0s 7ms/step - loss: -209.5669 - accuracy: 0.7449 - val_loss: -288.5092 - val_accuracy: 0.7143
Epoch 66/100
7/7 [==============================] - 0s 8ms/step - loss: -227.7367 - accuracy: 0.7449 - val_loss: -309.6748 - val_accuracy: 0.7143
Epoch 67/100
7/7 [==============================] - 0s 10ms/step - loss: -243.4825 - accuracy: 0.7449 - val_loss: -333.6317 - val_accuracy: 0.7143
Epoch 68/100
7/7 [==============================] - 0s 10ms/step - loss: -263.5146 - accuracy: 0.7449 - val_loss: -358.7585 - val_accuracy: 0.7143
Epoch 69/100
7/7 [==============================] - 0s 11ms/step - loss: -284.1725 - accuracy: 0.7449 - val_loss: -388.6797 - val_accuracy: 0.7143
Epoch 70/100
7/7 [==============================] - 0s 12ms/step - loss: -307.5190 - accuracy: 0.7449 - val_loss: -419.1585 - val_accuracy: 0.7143
Epoch 71/100
7/7 [==============================] - 0s 10ms/step - loss: -332.4459 - accuracy: 0.7449 - val_loss: -448.5020 - val_accuracy: 0.7143
Epoch 72/100
7/7 [==============================] - 0s 12ms/step - loss: -355.4951 - accuracy: 0.7449 - val_loss: -479.6859 - val_accuracy: 0.7143
Epoch 73/100
7/7 [==============================] - 0s 13ms/step - loss: -379.8598 - accuracy: 0.7449 - val_loss: -515.0883 - val_accuracy: 0.7143
Epoch 74/100
7/7 [==============================] - 0s 13ms/step - loss: -406.9363 - accuracy: 0.7449 - val_loss: -549.7076 - val_accuracy: 0.7143
Epoch 75/100
7/7 [==============================] - 0s 15ms/step - loss: -435.3905 - accuracy: 0.7449 - val_loss: -584.9807 - val_accuracy: 0.7143
Epoch 76/100
7/7 [==============================] - 0s 16ms/step - loss: -460.1920 - accuracy: 0.7449 - val_loss: -623.9116 - val_accuracy: 0.7143
Epoch 77/100
7/7 [==============================] - 0s 13ms/step - loss: -492.8279 - accuracy: 0.7449 - val_loss: -665.5052 - val_accuracy: 0.7143
Epoch 78/100
7/7 [==============================] - 0s 15ms/step - loss: -522.9547 - accuracy: 0.7449 - val_loss: -706.6966 - val_accuracy: 0.7143
Epoch 79/100
7/7 [==============================] - 0s 14ms/step - loss: -555.9731 - accuracy: 0.7449 - val_loss: -747.8891 - val_accuracy: 0.7143
Epoch 80/100
7/7 [==============================] - 0s 15ms/step - loss: -590.6376 - accuracy: 0.7449 - val_loss: -793.1577 - val_accuracy: 0.7143
Epoch 81/100
7/7 [==============================] - 0s 15ms/step - loss: -625.6415 - accuracy: 0.7449 - val_loss: -843.0423 - val_accuracy: 0.7143
Epoch 82/100
7/7 [==============================] - 0s 15ms/step - loss: -665.6286 - accuracy: 0.7449 - val_loss: -891.4582 - val_accuracy: 0.7143
Epoch 83/100
7/7 [==============================] - 0s 15ms/step - loss: -704.0343 - accuracy: 0.7449 - val_loss: -947.6315 - val_accuracy: 0.7143
Epoch 84/100
7/7 [==============================] - 0s 15ms/step - loss: -749.6123 - accuracy: 0.7449 - val_loss: -1004.9950 - val_accuracy: 0.7143
Epoch 85/100
7/7 [==============================] - 0s 19ms/step - loss: -791.3065 - accuracy: 0.7449 - val_loss: -1059.8710 - val_accuracy: 0.7143
Epoch 86/100
7/7 [==============================] - 0s 16ms/step - loss: -832.5110 - accuracy: 0.7449 - val_loss: -1117.5330 - val_accuracy: 0.7143
Epoch 87/100
7/7 [==============================] - 0s 14ms/step - loss: -880.4641 - accuracy: 0.7449 - val_loss: -1180.7903 - val_accuracy: 0.7143
Epoch 88/100
7/7 [==============================] - 0s 15ms/step - loss: -929.6542 - accuracy: 0.7449 - val_loss: -1249.8641 - val_accuracy: 0.7143
Epoch 89/100
7/7 [==============================] - 0s 16ms/step - loss: -979.6782 - accuracy: 0.7449 - val_loss: -1314.0890 - val_accuracy: 0.7143
Epoch 90/100
7/7 [==============================] - 0s 16ms/step - loss: -1029.1921 - accuracy: 0.7449 - val_loss: -1379.7522 - val_accuracy: 0.7143
Epoch 91/100
7/7 [==============================] - 0s 14ms/step - loss: -1080.1313 - accuracy: 0.7449 - val_loss: -1449.2565 - val_accuracy: 0.7143
Epoch 92/100
7/7 [==============================] - 0s 12ms/step - loss: -1134.9972 - accuracy: 0.7449 - val_loss: -1517.2115 - val_accuracy: 0.7143
Epoch 93/100
7/7 [==============================] - 0s 12ms/step - loss: -1186.1722 - accuracy: 0.7449 - val_loss: -1592.9360 - val_accuracy: 0.7143
Epoch 94/100
7/7 [==============================] - 0s 14ms/step - loss: -1250.8881 - accuracy: 0.7449 - val_loss: -1671.7328 - val_accuracy: 0.7143
Epoch 95/100
7/7 [==============================] - 0s 18ms/step - loss: -1308.1750 - accuracy: 0.7449 - val_loss: -1759.5634 - val_accuracy: 0.7143
Epoch 96/100
7/7 [==============================] - 0s 16ms/step - loss: -1375.4064 - accuracy: 0.7449 - val_loss: -1840.8536 - val_accuracy: 0.7143
Epoch 97/100
7/7 [==============================] - 0s 12ms/step - loss: -1438.4241 - accuracy: 0.7449 - val_loss: -1923.9763 - val_accuracy: 0.7143
Epoch 98/100
7/7 [==============================] - 0s 11ms/step - loss: -1502.1630 - accuracy: 0.7449 - val_loss: -2007.3031 - val_accuracy: 0.7143
Epoch 99/100
7/7 [==============================] - 0s 13ms/step - loss: -1565.2968 - accuracy: 0.7449 - val_loss: -2096.5242 - val_accuracy: 0.7143
Epoch 100/100
7/7 [==============================] - 0s 14ms/step - loss: -1638.8129 - accuracy: 0.7449 - val_loss: -2183.0068 - val_accuracy: 0.7143

In [41]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

3/3 - 0s - loss: -2.1711e+03 - accuracy: 0.6667 - 27ms/epoch - 9ms/step
Loss: -2171.097900390625, Accuracy: 0.6666666865348816